node {
    stage('Checkout') {
        echo 'Checkout'
        git branch: 'master' ,credentialsId: '1f1cba7c-f08e-4e21-95a3-244b75cbe861', url: 'https://zul@gtr.qmcai.com/qmbd/mgr.git'
    }
    stage('Build Image') {
        echo 'mvn build'
    }
    stage('Push Image') {
        echo 'Push Image'
    }
}