node {
    stage('Checkout') {
        steps {
            echo 'Checkout'
        }
    }
    stage('Build Image') {
        steps {
            echo 'mvn build'
        }
    }
    stage('Push Image') {
        echo 'Push Image'
    }
}